alter table del_documents add column delegation int(2) default null;
alter table del_documents add column hrdocumentvisible int(2) default null;

create table del_cron_invoicereports (id int(11) not null auto_increment,documentid int(11) default null,contractorid int(11) default null,workflowid int(11) default null,numer_faktury varchar(32) character set utf8 default null,netto varchar(16) character set utf8 default null,brutto varchar(16) character set utf8 default null,data_wystawienia varchar(16) character set utf8 default null,data_sprzedazy varchar(16) character set utf8 default null,data_platnosci varchar(16) character set utf8 default null,data_wplywu varchar(16) character set utf8 default null, numer_faktury_zewnetrzny varchar(64) character set utf8 default null,nazwa1 text character set utf8 default null,nazwa2 text character set utf8 default null,primary key(id))engine=innodb default charset=utf8 collate=utf8_unicode_ci;

alter table del_cron_invoicereports add column nip varchar(16) character set utf8 default null;
alter table del_cron_invoicereports add column departmentname varchar(128) character set utf8 default null;

create table del_trigger_workflowsearch(id int(11) not null auto_increment,workflowid int(11) default null,documentid int(11) default null,numer_faktury varchar(32) character set utf8 default null,netto varchar(32) character set utf8 default null,brutto varchar(32) character set utf8 default null,data_wystawienia varchar(32) character set utf8 default null,data_sprzedazy varchar(32) character set utf8 default null,data_platnosci varchar(32) character set utf8 default null,data_wplywu varchar(43) character set utf8 default null,numer_faktury_zewnetrzny varchar(64) character set utf8 default null,contractorid int(11) default null,nazwa1 text character set utf8 default null,nazwa2 text character set utf8 default null,workflowstepnote text character set utf8 default null,nip varchar(16) character set utf8 default null,primary key(id))engine=innodb default charset=utf8 collate=utf8_unicode_ci;

create table del_trigger_workflowsteplists (id int(11) not null auto_increment,workflowid int(11) default null,documentid int(11) default null,workflowcreated date,documentname text character set utf8 default null,stepdescriptionid int(2) default null,stepdescriptiondraft int(2) default null,stepcontrollingid int(2) default null,stepcontrollingdraft int(2) default null,stepapproveid int(2) default null,stepapproveddraft int(2) default null,stepaccountingid int(2) default null,stepaccountingdraft int(2) default null,stepacceptid int(2) default null,stepacceptdraft int(2) default null,stependid int(2) default null,endeddate datetime,contractorname text character set utf8 default null,primary key(id))engine=innodb default charset=utf8 collate=utf8_unicode_ci;

alter table del_trigger_workflowsteplists add column brutto varchar(32) character set utf8 default null;alter table del_trigger_workflowsteplists add column workflowstepnote text character set utf8 default null;
alter table del_trigger_workflowsteplists add column delegation int(2) default 0;
alter table del_trigger_workflowsteplists add column hr_documentvisible int(2) default 1;
